### ISSUE TITLE
Move JS modules to separate repos (e.g., video color tracker)

### ISSUE THREAD

**Issue by tannerhodges** [madebymode/mode-front-end#37]
- [ ] mode-analytics
- [ ] mode-balance-text
- [x] mode-color-tracker → [video-color-tracker](https://github.com/madebymode/video-color-tracker)
- [ ] mode-menu-aim
- [ ] mode-navigation
- [ ] mode-video
